spring:
  application:
    name: cloud-server
  security:
    user:
      name: greg
      password: 12345


server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
