spring:
  application:
    name: ms-person
  rabbitmq:
    host: localhost
    port: 5672
    username: greg
    password: 12345

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://greg:12345@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

rabbitmq:
  person:
    exchange: person-exchange
    routing-key: person-routing-key

