spring:
  application:
    name: ms-person
  rabbitmq:
    host: localhost
    port: 5672
    username: greg
    password: 12345

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  
